apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: default
spec:
  secretName: tls-secret
  dnsNames:
  - kube.leevi.co.kr
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - kube.leevi.co.kr
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer