apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  selector:
    matchLabels:
      tier: "silver"
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
