apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 1@1.net
    privateKeySecretRef:
      name: letsencrypt-2
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux