apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-demo-rc
spec:
  replicas: 3
  selector:
    app: spring-demo
  template:
    metadata:
      name: spring-demo-pod
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: 8byte/app-demo:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

