apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-main
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
      role: main
      tier: backend
    replicas: 1
    template:
      metadata:
        labels:
          app: zookeeper
          role: main
          tier: backend
      spec:
        containers:
        - name: main
          image: zookeeper
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            ports: 2181




