apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - name: terry-path
        mountPath: /data
      volumes:
      - name: terry-path
        persistentVolumeClam:
          className: pv-claim-demo