apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
spec:
  storageClassName:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: pv-demo-disk
    fsType: ext4
